### ISSUE TITLE
Writing to the "." key in an object throws an Automerge error "RangeError: key must not be an empty string"

### ISSUE THREAD

**Issue by svdvonde** [onsetsoftware/automerge-patcher#6]
I am writing some property-based tests for a project using the [fast-check](https://github.com/dubzzz/fast-check) library. It likes to generate random objects like: 

```ts
{"!":{"!":{"!":{".": false}}}}
```

A counterexample that the testing library found used an object such as the one above, which at some point generated the error `RangeError: key must not be an empty string` from somewhere in the Automerge wasm. I was able to narrow things down, and it seems to be introduced by automerge-patcher.

Using automerge-patcher, code that makes Automerge throw the error:

```ts
const data = Automerge.from({".": 0});
const toApply: Automerge.Patch = {
    action: "put",
    path: ["."],
    value: 1
}
Automerge.change(data, (d) => {
    AutomergePatcher.patch(d, toApply);
});
```

The same code (without automerge-patcher) is accepted by Automerge: 

```ts
const data = Automerge.from({".": 0});
Automerge.change(data, (d) => {
    d["."] = 1
});
```

**Comment by acurrieclark** [comment]
Interesting. The path gets turned into dot paths internally eg `['base', 'path'] => 'base.path'`.

This would effectively filter any paths which include `.`, resulting in an empty key here. Not sure how to deal with that specifically, but it should probably be possible.

**Comment by svdvonde** [comment]
I suppose paths would have to be treated exclusively as arrays. The`dot-path-value` (used in `./src/helpers.ts`) does not seem to support using paths specified as arrays. Alternatives exist, for example (in no particular order):

 * [object-path](https://github.com/mariocasciaro/object-path)
 * Lodash's [_.get](https://lodash.com/docs/#get) and [_.set](https://lodash.com/docs/#set)
 * [get-object-value](https://www.npmjs.com/package/get-object-value) and [set-object-value](https://www.npmjs.com/package/set-object-value)
 * [object-path-get](https://www.npmjs.com/package/object-path-get) and [object-path-set](https://www.npmjs.com/package/object-path-set)

**Comment by acurrieclark** [comment]
It doesn’t, no. I hadn’t thought of swapping out the library; it might be the best option.

any chance you could add a PR with one of your failing tests and I will get a solution sorted?

**Comment by svdvonde** [comment]
Will do, first thing tomorrow morning 👍
