### ISSUE TITLE
`RangeError` when applying a `splice` patch on a path `[ "/!", 0 ]`

### ISSUE THREAD

**Issue by svdvonde** [onsetsoftware/automerge-patcher#9]
Hi,

I am writing some property-based tests for a research project using the [fast-check](https://github.com/dubzzz/fast-check) library.  It has uncovered a `RangeError` which I think is caused by automerge-patcher.

Consider the following Automerge code where a string `" "` is assigned to path `["/!"]`. 
```ts
    let testDoc = Automerge.from({"/!": ""});
    testDoc = Automerge.change(testDoc, (d) => { d['/!'] = " "; });
```

Automerge generates the following patches for this change: 

```ts
[
  { action: 'put', path: [ '/!' ], value: '' },
  { action: 'splice', path: [ '/!', 0 ], value: ' ' }
]
```

When I recreate this situation using `automerge-patcher`, it throws an error: `RangeError: Cannot splice: RangeError: invalid op for object of type 'map'`. The following code reproduces the error (stacktrace added below).

```ts
    let testDoc = Automerge.from({"/!": ""});
    testDoc = Automerge.change(testDoc, (d) => {
        AutomergePatcher.patch(d, { action: 'splice', path: [ '/!', 0 ], value: " " });
    });
```

```text
file:///Users/sam/VUB/Projects/securemerge/node_modules/@automerge/automerge/dist/mjs/next.js:178
        throw new RangeError(`Cannot splice: ${e}`);
              ^

RangeError: Cannot splice: RangeError: invalid op for object of type `map`
    at Module.splice (file:///Users/sam/VUB/Projects/securemerge/node_modules/@automerge/automerge/dist/mjs/next.js:178:15)
    at Module.j (file:///Users/sam/VUB/Projects/securemerge/node_modules/@onsetsoftware/automerge-patcher/dist/automerge-patcher.js:93:9)
    [...]
```

Using `"@onsetsoftware/automerge-patcher": "0.12.0"`

**Comment by acurrieclark** [comment]
`splice` in automerge uses `/` under the hood to create its paths, so I think this is at the automerge level. I don’t think you can have forwardslashes in your path.

if you can’t recreate the same issue without patcher, i will take another look.

**Comment by svdvonde** [comment]
I'm unable to reproduce it using only Automerge. The operations that I can come up with seem to work just fine. For example:

```ts
    let testDoc = Automerge.from({"/!": {"/x": ""}});
    testDoc = Automerge.change(testDoc,
        {patchCallback: (patches) => console.debug(patches)},
        (d) => { d['/!']['/x'] = "x"; });

    console.debug(testDoc);
```

Prints the following output:

```ts
[
  { action: 'put', path: [ '/!', '/x' ], value: '' },
  { action: 'splice', path: [ '/!', '/x', 0 ], value: 'x' }
]
{ '/!': { '/x': 'x' } }
```

**Comment by acurrieclark** [comment]
You aren’t using `splice` in your change function there. You are just setting the property directly.

**Comment by svdvonde** [comment]
You're right. I was able to reproduce it for Automerge when explicitly using `Automerge.splice`. 

My mistake was thinking that when automerge produced a `splice` patch, that it would have executed a `splice` operation internally. My apologies!

**Comment by acurrieclark** [comment]
No problem!

Automerge is actually performing a splice internally. When you set a string value to another string value it first creates and empty string then splices in the new value. However, that all happens internally. 

 The issue is that the JavaScript splice api takes a path as an array which is then joined with forwardslashes before it is passed on to the WASM internals. There has been some discussion of alternative methods of describing the path, but for now it just means you can’t call splice on a path which already includes a forwardslash.

**Comment by svdvonde** [comment]
Would it be helpful to open an Automerge issue about this just to keep track? I don't particularly need it fixed, but throwing an internal `RangeError` (as long as this implementation detail exists) is maybe not ideal.

**Comment by acurrieclark** [comment]
There is [one already](https://github.com/automerge/automerge/issues/825), so I think we are ok there. 

By all means give it a nudge though!
